baseURL = "https://zhugexiuqi.github.io/"
title = "我的博客"
theme = "PaperMod"

# 可选：设置默认语言、分页等
defaultContentLanguage = "zh-cn"
paginate = 5




[menu]
  [[menu.main]]
    identifier = "categories"
    name = "全部分类"    # 菜单上显示的文字
    url = "/categories/"  # 点击后跳转的地址
    weight = 10           # 菜单显示顺序，数字越小越靠左


    [params]
  # 基础信息
  author = "你的名字"                     # 网站作者
  description = "这是我的博客"             # 网站描述，用于SEO
  keywords = ["博客", "技术"]             # 网站关键词

    disableSpecial1stPost = true